- name: yum update
  yum: name=* state=latest

- name: install docker
  yum: name=docker state=latest

- name: create docker group
  group: name=docker

- name: add user to docker group
  user: name=vagrant groups=docker append=yes

- name: up docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: install vim
  yum: name=vim state=latest