- name: yum update
  yum: name=* state=latest

- name: install firewalld for disable
  yum: name=firewalld state=latest

- name: stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: install vim
  yum: name=vim state=latest

- name: install nodejs
  yum: name=nodejs enablerepo=epel